apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter-deployment
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.18.0
        ports:
        - containerPort: 9104
        env:
        - name: DATA_SOURCE_NAME
          value: "exporter:exporter_password@(mysql-service.devops.svc.cluster.local:3306)/"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-service
  namespace: devops
spec:
  selector:
    app: mysql-exporter
  ports:
  - port: 9104
    targetPort: 9104
