apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Prometheus lui-mÃªme
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      # Spring Boot App (AVEC context-path)
      - job_name: "spring-boot"
        metrics_path: /student/actuator/prometheus
        static_configs:
          - targets:
              - spring-service.devops.svc.cluster.local:8080

      # Node Exporter
      - job_name: "node-exporter"
        static_configs:
          - targets:
              - node-exporter-service.devops.svc.cluster.local:9100

      # MySQL Exporter
      - job_name: "mysql"
        static_configs:
          - targets:
              - mysql-exporter-service.devops.svc.cluster.local:9104
